FROM ubuntu:16.04
MAINTAINER sbofgayschoolbupaanything "1532422769@qq.com"

RUN requirement='libc6-dev make wget gcc python3-pip python3-dev' \
    && apt-get update \
    && apt-get install -y $requirement
    && cd /usr/local/bin \
    && ln -s /usr/bin/python3 python \
    && pip3 install --upgrade pip \
    && cd ??? \
    && pip3 install requirements.txt